name: spotify
description: An incomplete dart library for interfacing with the Spotify Web API.
version: 0.5.1
homepage: https://github.com/rinukkusu/spotify-dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.0
  oauth2: ^2.0.0
  pedantic: ^1.9.0

dev_dependencies:
  test: ^1.5.1
  build_runner: ^1.1.1
  json_serializable: ^4.0.0
